"use client";

import { useEffect, useState } from "react";
import apiClient from "@/lib/apiClient";
import { ShieldAlert, CheckCircle2, Clock, Play, User, Briefcase, ExternalLink, ShieldCheck, XCircle } from 'lucide-react';
import { Card, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { motion } from "framer-motion";
import { useRouter } from "next/navigation";

export default function ApprovalsPage() {
  const [approvals, setApprovals] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeAction, setActiveAction] = useState<string | null>(null);
  const router = useRouter();

  const fetchApprovals = async () => {
    setError(null);
    try {
      const res = await apiClient.get("/approvals/");
      setApprovals(res.data || []);
    } catch (e: any) {
      setError(e?.response?.data?.detail || "Failed to load approvals queue.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchApprovals();
  }, []);

  const handleAction = async (id: string, action: "approve" | "reject" | "execute") => {
    setActiveAction(`${id}:${action}`);
    setError(null);
    try {
      await apiClient.post(`/approvals/${id}/${action}`);
      await fetchApprovals();
    } catch (e: any) {
      setError(e?.response?.data?.detail || `Failed to ${action} proposal.`);
    } finally {
      setActiveAction(null);
    }
  };

  if (loading) {
    return <div className="p-8 text-center text-xs font-mono text-text-muted">Loading Human-In-The-Loop approvals queue...</div>;
  }

  return (
    <div className="flex flex-col space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col gap-2">
        <div className="inline-flex items-center gap-2 text-xs font-mono font-bold uppercase tracking-widest text-amber-400">
          <ShieldAlert size={16} />
          <span>Security Authorization Queue</span>
        </div>
        <h1 className="font-display text-3xl font-extrabold tracking-tight text-white">
          Human-In-The-Loop Approvals
        </h1>
        <p className="text-xs text-text-secondary">
          Review, authorize, or execute candidate actions generated by the AI agent before direct dispatch.
        </p>
      </div>

      {error && (
        <div className="rounded-2xl border border-rose-500/20 bg-rose-500/10 p-4 text-xs text-rose-400 font-medium">
          {error}
        </div>
      )}

      {approvals.length === 0 ? (
        <Card className="border-white/10 bg-[#0e111a]/80 border-dashed rounded-2xl">
          <CardContent className="flex flex-col items-center justify-center p-12 text-center text-text-muted">
            <CheckCircle2 size={48} className="mb-4 text-emerald-400 opacity-40" />
            <p className="text-base font-bold text-white">Queue Empty</p>
            <p className="text-xs text-text-secondary mt-1 max-w-md">No pending action proposals requiring recruiter review. Agent-generated outreach will appear here.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {approvals.map((proposal, idx) => (
            <motion.div
              key={proposal.id}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.08, duration: 0.3 }}
            >
              <Card className="border-white/10 bg-[#0e111a]/90 backdrop-blur-2xl shadow-xl rounded-2xl overflow-hidden">
                <div className="h-1 w-full bg-gradient-to-r from-amber-500 via-indigo-500 to-emerald-500" />
                <CardContent className="flex flex-col p-6 md:flex-row md:items-start md:justify-between gap-6">
                  <div className="flex-1 space-y-4">
                    <div className="flex items-center gap-3">
                      <span className="font-mono text-xs font-bold tracking-widest text-amber-400 uppercase bg-amber-500/10 px-2.5 py-1 rounded-md border border-amber-500/20">
                        {proposal.action_type}
                      </span>
                      <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-0.5 text-xs font-mono font-bold ${
                        proposal.status === 'PENDING_APPROVAL' ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' : 
                        proposal.status === 'APPROVED' ? 'bg-indigo-500/10 text-indigo-300 border border-indigo-500/20' :
                        proposal.status === 'EXECUTED' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' :
                        'bg-rose-500/10 text-rose-400 border border-rose-500/20'
                      }`}>
                        {proposal.status === 'PENDING_APPROVAL' && <Clock size={12} />}
                        {proposal.status === 'APPROVED' && <CheckCircle2 size={12} />}
                        {proposal.status === 'EXECUTED' && <Play size={12} />}
                        {proposal.status}
                      </span>
                    </div>

                    {/* Relational Candidate & Job Pills */}
                    <div className="flex flex-wrap gap-2.5 text-xs">
                      {proposal.target_id && (
                        <button 
                          onClick={() => router.push(`/candidates/${proposal.target_id}`)}
                          className="flex items-center gap-1.5 rounded-xl border border-indigo-500/30 bg-indigo-500/10 px-3 py-1.5 font-semibold text-indigo-300 hover:bg-indigo-500/20 transition-colors text-xs"
                        >
                          <User size={13} />
                          <span>Candidate: {proposal.candidate_name || `Candidate (${proposal.target_id.substring(0,8)})`}</span>
                          <ExternalLink size={11} />
                        </button>
                      )}

                      {proposal.job_id && (
                        <button 
                          onClick={() => router.push(`/jobs/${proposal.job_id}`)}
                          className="flex items-center gap-1.5 rounded-xl border border-purple-500/30 bg-purple-500/10 px-3 py-1.5 font-semibold text-purple-300 hover:bg-purple-500/20 transition-colors text-xs"
                        >
                          <Briefcase size={13} />
                          <span>Job: {proposal.job_title || 'View Requisition'}</span>
                          <ExternalLink size={11} />
                        </button>
                      )}
                    </div>

                    <div>
                      <span className="text-text-muted uppercase text-[10px] font-mono font-bold tracking-widest block mb-1">Agent Justification Reason</span>
                      <p className="text-xs text-white bg-white/5 p-3.5 rounded-xl border border-white/10 leading-relaxed font-sans">{proposal.reason}</p>
                    </div>
                    
                    {proposal.payload && (
                      <div className="rounded-xl border border-white/10 bg-white/5 p-4 text-xs font-mono">
                        <div className="flex items-center gap-2 mb-2 pb-2 border-b border-white/10">
                          <span className="text-text-muted font-bold text-[10px] uppercase tracking-wider">Proposal Message Payload</span>
                        </div>
                        {proposal.payload.recipient && <p className="mb-1"><span className="text-text-muted">Recipient:</span> <span className="text-indigo-400 font-semibold">{proposal.payload.recipient}</span></p>}
                        {proposal.payload.subject && <p className="mb-2"><span className="text-text-muted">Subject:</span> <span className="text-white font-semibold">{proposal.payload.subject}</span></p>}
                        {proposal.payload.body && (
                          <div className="mt-3">
                            <span className="text-text-muted block mb-1 text-[10px] uppercase">Body Template:</span>
                            <pre className="whitespace-pre-wrap text-text-secondary font-sans text-xs bg-black/40 p-3 rounded-lg border border-white/10 leading-relaxed">{proposal.payload.body}</pre>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                  
                  {/* Action Button Controls */}
                  <div className="flex flex-col items-end gap-3 min-w-[200px] border-t border-white/10 pt-4 md:border-t-0 md:border-l md:pt-0 md:pl-6">
                    {proposal.status === 'PENDING_APPROVAL' && (
                      <div className="flex w-full flex-col gap-2">
                        <Button 
                          onClick={() => handleAction(proposal.id, "approve")}
                          disabled={activeAction === `${proposal.id}:approve`}
                          className="w-full bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg font-semibold rounded-xl text-xs"
                          isLoading={activeAction === `${proposal.id}:approve`}
                          leftIcon={<ShieldCheck size={15} />}
                        >
                          Approve Action
                        </Button>
                        <Button 
                          variant="secondary"
                          onClick={() => handleAction(proposal.id, "reject")}
                          disabled={activeAction === `${proposal.id}:reject`}
                          className="w-full hover:bg-rose-500/20 hover:text-rose-400 hover:border-rose-500/40 rounded-xl text-xs"
                          isLoading={activeAction === `${proposal.id}:reject`}
                          leftIcon={<XCircle size={15} />}
                        >
                          Reject
                        </Button>
                      </div>
                    )}
                    
                    {proposal.status === 'APPROVED' && (
                      <div className="w-full">
                        <Button 
                          onClick={() => handleAction(proposal.id, "execute")}
                          disabled={activeAction === `${proposal.id}:execute`}
                          className="w-full bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg font-semibold rounded-xl text-xs"
                          leftIcon={<Play size={15} />}
                          isLoading={activeAction === `${proposal.id}:execute`}
                        >
                          Execute Now
                        </Button>
                      </div>
                    )}
                    
                    {proposal.status === 'EXECUTED' && (
                      <div className="flex w-full flex-col items-center justify-center p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-center">
                        <CheckCircle2 className="text-emerald-400 mb-1" size={22} />
                        <span className="text-emerald-400 font-mono font-bold text-xs uppercase tracking-widest">Executed</span>
                        <p className="mt-1 text-[11px] text-emerald-400/80">Action completed safely.</p>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
